### ISSUE TITLE
The Poet's Mind

### ISSUE THREAD

**Issue by chuna** [humitos/turtle-confusion-es#13]
On page 40, Puzzle 29, it appears the second stanza of a poem by Alfred Lord Tennyson, The Poet's Mind. 
I would like to find an "official" Spanish translation of this poem, as in translating it myself I would feel even disrespectful. Therefore, Puzzle 29 translation will be left incomplete until I find the poem's published version in Spanish.

**Comment by humitos** [comment]
To create a footnote you have to add [#]_ where you want the super index number and then you have to add the reference paragraph in a new line at the bottom of the file. For example:

(....)

Respiró hondo y leyó en voz alta [#]_:

(.. the poem goes here ...)

(.. more paragraphs go here ...)

<bottom of the file>

.. [#] N. del T.: here you should write the paragraph explaining the footnote.

**Comment by chuna** [comment]
The poem was finally translated without the official references we were looking for. However, assessment was asked. 
Done here 96180818659825b208e06a972e5780df1f880ef4

**Comment by humitos** [comment]
The N. del T.: was pushed here: fbd1db95504f516556f02700be5a456411ff87e1
