### ISSUE TITLE
Mathematics is singular or plural

### ISSUE THREAD

**Issue by humitos** [humitos/turtle-confusion-es#17]
There are some pages (Prologue, for example) where "mathematics" is translated as "matemáticas" and "matemática" in the same page. 
- Why we are making this distinction?
- What is the correct way to translate it?

**Comment by chuna** [comment]
Having thought about it thoroughly, I believe that translating mathematics in the plural form in Spanish suits better: "matemáticas"

**Comment by chuna** [comment]
Revised and changed all files containing "matemática" in the singular, now they contain "matemáticas" in the plural, as the spelling shows

**Comment by humitos** [comment]
Done here: 87fb098940c3c408a99b01526449b3faf9968ad1 and 3821a93a4bf66b00140a07c1bdda4f9333073d88
