### ISSUE TITLE
Strange sentence

### ISSUE THREAD

**Issue by humitos** [humitos/turtle-confusion-es#20]
I'm not sure why, but this sentence doesn't sound good to me (this is in the introduction):

"Cuando leo el manuscrito me da la impresión de que los puzzles Logo pueden ser demasiado fáciles para cualquiera lo suficientemente avanzado para resolver los acertijos."

**Comment by chuna** [comment]
How about this: "Cuando leo el manuscrito, me da la impresión de que las figuras de Logo pueden ser demasiado fáciles para cualquiera que esté lo suficientemente avanzado para resolver los acertijos"

Will this do? does it sound a little better?

**Comment by humitos** [comment]
Yes, it's much more readable!

**Comment by chuna** [comment]
Revised and changed

**Comment by humitos** [comment]
Done here: 87fb098940c3c408a99b01526449b3faf9968ad1
