### ISSUE TITLE
Translation of Logo commands

### ISSUE THREAD

**Issue by chuna** [humitos/turtle-confusion-es#22]
On page 55, in the How To Use This Booklet section, there is a list on Logo commands and their meaning.
Is Logo a language that is available to use in Spanish?
Have Logo commands been translated into Spanish? I found some commands translated. Not all of them.

**Comment by humitos** [comment]
Yes, Logo is available in Spanish. I think we should translate them and take the translation from the Turtle Art Activity that they have already translated these commands.

**Comment by humitos** [comment]
Taking a look at that page I realized that we can't translate those commands because they refer to the LCSI Logo Apple and it has a syntax that we can't change.

We decide to change a bit that paragraph to mention Turtle Art maybe and use the Spanish version of its commands adding a N. del T. at the bottom of the page explaining why we did that change.

**Comment by humitos** [comment]
There are some Logo Commands in Puzzle 4 that we should take a look as well. They are already translated.

**Comment by humitos** [comment]
Those commads are translated as:
- adelante
- atrás
- izquierda
- derecha
- subir pluma
- bajar pluma
- repetir
- limpiar

I didn't find TO, END, EDIT but I guess that they are not implemented in Turtle Art because the way that Logo is used is different. I will ask to Walter Bender for more information

**Comment by humitos** [comment]
After a talk with Walter, he told me that TO and END are used to create a new procedure but in Turtle Art they are created using the ACTION block and it's translated as "acción" so we should use it in our translation.

Regarding the EDIT command, it is not used at all in Turtle Art. We can omit it from the book.

Melina, please, go ahead with this modifications.

**Comment by chuna** [comment]
The section has been revised and modified following the translation available in Turtle Art, a Translator footnote has been created

**Comment by humitos** [comment]
The first part is done here: 145d91733773de6c822697b64e7cc1905ec33255 and 5801f317cad8547bcdd24f2c13cfddc74c214a21 but there are some mistakes to solve.
- I would like to modify the N. del T. for something like this

"Se decidió traducir los comandos de LSCI Apple Logo en comandos de Turtle Art (una actividad de la plataforma educativa Sugar), ya que la implementación de LSCI Apple de Logo está en desuso. Para que el grupo de comandos sea consistente con los que existen en Turtle Art, los comandos TO (PARA), END (FIN) y EDIT (EDITOR), fueron reemplazados por ACCIÓN."
- The word "crear" is missing

"el comando que se necesita para CREAR procedimientos"
- A "-" was deleted and this made the table to not work anymore

**Comment by chuna** [comment]
The table has been fixed (successfully I think).
The N. del T. has been a little modified, as well.

**Comment by humitos** [comment]
Done here: 0e1da2cc2b4974a8c172b0f843cb09a49bf0c97a and dcdd6404cd4bc86331b32dd712bc3a45ea62c207

**Comment by humitos** [comment]
Meli, please, remember to add the links to the commit SHA on the issue so we can refer to it in the future.

You can get it (or them) from the "Code" tab and then in "Commits" tab. There you will find an icon like a common "Paste" and when you hover it with the mouse, "Copy SHA" will appear. Click on it and then Control + V on the issue.

If you don't understand my explanation, that I'm not sure it was quite good, please ask me.
