### ISSUE TITLE
Paragraph with Translation Acknowledgements

### ISSUE THREAD

**Issue by humitos** [humitos/turtle-confusion-es#25]
It would be great to have a page that mentions all the people that help us to make this translation possible as well as the software resources that we use to create the HTML and PDF versions

**Comment by chuna** [comment]
I entirely agree.

**Comment by humitos** [comment]
People that help us on this translation: Leonardo De Luca, Manuel Quiñones, Gonzalo Odiard, Barry Newell, Roberto Alsina, Sandra Bayona, Carlos Glücklich...

Maybe I'm missing someone else, please add him/her...

**Comment by humitos** [comment]
Escribí éste párrafo. ¿Alguna sugerencia / comentario?

Nos gustaría agradecer a varias personas que colaboraron de alguna u otra manera para que ésta traducción sea posible. En primer lugar, a Barry Newell por haber escrito un excelente libro como éste y autorizar la traducción del mismo. También a Manuel Quiñones, quien diseñó la tapa del libro. Sandra Bayona y Carlos Glücklich quienes nos dieron una mano con la traducción del poema de la figura 29, como así también a Leonardo De Luca que nos ayudó con algunas sugerencias sobre la traducción. Finalmente, y no por eso menos importante, a Roberto Alsina por su magnífico trabajo en el software utilizado para crear la versión PDF de éste libro llamado `rst2pdf`_ y a Gonzalo Odiard por estimular éste proyecto.

¡Muchas gracias a todos los que colaboraron! Estamos muy contentos con éste proyecto.

.. _rst2pdf: http://rst2pdf.ralsina.com.ar/

**Comment by chuna** [comment]
"este" me parece que no lleva acento cuando funciona como modificador de su sustantivo, creo que toma acento ùnicamente cuando funciona como pronombre: Me llevo éstos, por ej... entonces los borro...
El alumno de Sandra de Villa LIbertador, se llama Danilo, pero no estoy segura de si el apellido es Heinz o Heinze :S

---

 De: Manuel Kaufmann notifications@github.com
Para: humitos/turtle-confusion-es turtle-confusion-es@noreply.github.com 
CC: Melina Lucía Coronel melina_coronel@yahoo.com.ar 
Enviado: sábado, 6 de octubre de 2012 14:08
Asunto: Re: [turtle-confusion-es] Paragraph with Translation Acknowledgements (#25)

Escribí este párrafo. ¿Alguna sugerencia / comentario?
Nos gustaría agradecer a varias personas que colaboraron de alguna u otra manera para que esta traducción sea posible. En primer lugar, a Barry Newell por haber escrito un excelente libro como éste y autorizar la traducción del mismo. También a Manuel Quiñones, quien diseñó la tapa del libro. Sandra Bayona y Carlos Glücklich quienes nos dieron una mano con la traducción del Poema de la Figura 29, como así también a Leonardo De Luca que nos ayudó con algunas sugerencias sobre la traducción. Finalmente, y no por eso menos importante, a Roberto Alsina por su magnífico trabajo en el software utilizado para crear la versión PDF de este libro llamado rst2pdf_ y a Gonzalo Odiard por estimular este proyecto.
¡Muchas gracias a todos los que colaboraron! Estamos muy contentos con este proyecto.
.. _rst2pdf: http://rst2pdf.ralsina.com.ar/

**Comment by manuq** [comment]
chuna tiene razón

**Comment by humitos** [comment]
OK. Corrijo esas cositas y le mando un mail a Sandra para preguntarle cómo es el apellido de Danilo

**Comment by humitos** [comment]
La nueva versión corregida:

Nos gustaría agradecer a varias personas que colaboraron de alguna u otra manera para que esta traducción sea posible. En primer lugar, a Barry Newell por haber escrito un excelente libro como éste y autorizar la traducción del mismo. También a Manuel Quiñones, quien diseñó la tapa del libro. Danilo Hein y Carlos Glücklich quienes nos dieron una mano con la traducción del poema de la figura 29, como así también a Leonardo De Luca que nos ayudó con algunas sugerencias sobre la traducción. Finalmente, y no por eso menos importante, a Roberto Alsina por su magnífico trabajo en el software utilizado para crear la versión PDF de este libro llamado `rst2pdf`_ y a Gonzalo Odiard por estimular este proyecto.

¡Muchas gracias a todos los que colaboraron! Estamos muy contentos con este proyecto.
