### ISSUE TITLE
"Further steps" section

### ISSUE THREAD

**Issue by humitos** [humitos/turtle-confusion-es#27]
I don't like the translation used for the title "Further steps". It was translated as "Siguientes pasos", but there is something that doesn't sound good to me in that title.

It's a difficult sentence to translate and I don't have the best option, but at least I have another one to start the discussion :)

I would use "Próximos pasos" for the title of this section.

**Comment by chuna** [comment]
A suitable variation can also be "Pasos a seguir".  However, the main idea is to interpret the phrase as 'there is more investigation to dive into', more knowledge to discover, and not as a set of instructions to follow, as "Pasos" might be wrongly taken.

**Comment by humitos** [comment]
Yes, I totally agree with you.

Between the given options that we have: "Próximos pasos" and "Pasos a seguir" I prefer the first one. But we can wait for more variations to come and maybe we can ask to someone else.

**Comment by chuna** [comment]
Looking at other translations, the contexts and meanings do not match the one we need, or the translation is not appealing: "las próximas etapas"... 
If we are to choose from "Próximos pasos" and "Pasos a seguir" the obvious best is "Próximos pasos". The important thing is, again, that the idea underlying the title is the possibility of diving in a new field of knowledge...difficult to achieve through the title alone...

**Comment by humitos** [comment]
e6c2387a4234abda54e8bbd1e4d924ea1440ab0e
