### ISSUE TITLE
Translator footnotes 1

### ISSUE THREAD

**Issue by chuna** [humitos/turtle-confusion-es#28]
When the translation of "The Poet's Mind"  is found, can it be referred to? Can the book where the translation was found be quoted?

**Comment by humitos** [comment]
Yes. We can use a clickeable super index (in the digital version) [1] that points to the bottom of the page, where it should say something like:

"[1] N. del T.: blah blah blah"

Can you write the "blah blah blah" paragraph in the meantime?

I have to reasearch about how to do that in the HTML and PDF versions

**Comment by humitos** [comment]
This issue is duplicated. Closing. Please, refer to this one: #13
