### ISSUE TITLE
Translator footnotes 2

### ISSUE THREAD

**Issue by chuna** [humitos/turtle-confusion-es#29]
In the section "How to use this Booklet", there is a set of Logo commands mentioned. As they belong to  Apple LCSI, and I have been told that they can not be translated into Spanish, I have decided that the translation will be consistent to the sugarlabs version of Turtle art containing the commands in question. The footnote will make reference to this fact.

**Comment by humitos** [comment]
This issue is duplicated. Please, refer to this one: #22
