### ISSUE TITLE
"Pointer"

### ISSUE THREAD

**Issue by chuna** [humitos/turtle-confusion-es#5]
On page 18, puzzle 7, it appears the explanation of the word "pointer", as follows 

"A pointer is a riddle that has a single number as its solution; the number is the
sequence-number of another puzzle in this booklet. In some cases the related
puzzle will be a harder puzzle, in some cases it will be an easier puzzle."

I wonder if this concept is specifically related to programming. Consecuently, it represents a challenge to translate.

**Comment by leorockway** [comment]
Although pointer in programming can mean something in particular (a C pointer, for instance), in this case it just means a clue.
From WordReference's entry on "pointer":
 
    (clue, signal) pista f;
    ~ TO sth indicador m de algo

```
(tip) idea f, sugerencia f
```
