### ISSUE TITLE
Flatlander Sentry

### ISSUE THREAD

**Issue by chuna** [humitos/turtle-confusion-es#6]
On page 20, puzzle 09, I found a difficulty translating the riddle, as it contains the compound noun Flatlander Sentry. It breaks the rhyme in Spanish, but the problem is that I really do not understand the MEANING. Is it related to mountaineering?  or is it the name of a place?

**Comment by leorockway** [comment]
Flatlander is capitalized, but sentry isn't. I believe that Flatlander could be a reference to Flatland: A Romance of Many Dimensions. Since this book is popular among programmers, the author could be paying homage to it.
Without knowing the answer to the riddle it's difficult to be sure, but I suggest translating it as centinela de Planilandia. How to make it rhyme... that's a completely different issue.

**Comment by chuna** [comment]
Thank you Leonardo! This is of great help, there are things in the book that seem to be making reference to programming matters, and as I am not ver into the subject I tend to doubt whether the translation requires more specific terminology or it is just what it is! (as in the case of "pointer")
About the rhymes: I am thinking of trying to figure out a neat way to make the riddles rhyme in the near future, it is my homework, I don't know HOW it will turn out, but at least I can try. 
Thank you for taking the time to have a look at the issues. You'll probably be hearing from us :)
Regards, 
Melina

---

 De: leorockway notifications@github.com
Para: humitos/turtle-confusion-es turtle-confusion-es@noreply.github.com 
CC: Melina Lucía Coronel melina_coronel@yahoo.com.ar 
Enviado: miércoles, 29 de agosto de 2012 23:24
Asunto: Re: [turtle-confusion-es] Flatlander Sentry (#6)

Flatlander is capitalized, but sentry isn't. I believe that Flatlander could be a reference to Flatland: A Romance of Many Dimensions. Since this book is popular among programmers, the author could be paying homage to it.
Without knowing the answer to the riddle it's difficult to be sure, but I suggest translating it as centinela de Planilandia. How to make it rhyme... that's a completely different issue.

**Comment by humitos** [comment]
This is the book that leorockway mentioned: https://es.wikipedia.org/wiki/Flatland,_romance_of_many_dimensions

**Comment by chuna** [comment]
The translation of Flatlander sentry ended up being "centinela de Planilandia". The riddle could even get a rhyme

**Comment by humitos** [comment]
Done here: 025f2e63a09102e6f78bdbeb81e14870ad47c57d
